### ISSUE TITLE
如何在本地部署该服务器

### ISSUE THREAD

**Issue by pk49800** [mingwiki/anki-sync-server#1]
请教一下如何在本地部署服务器（mac环境）供自己使用？只有电脑和手机有使用anki这个需求。nginx配置文件应该怎么改呢？其他还有需要修改的地方吗。谢谢。

**Comment by mingwiki** [comment]
因为用的是docker所以mac跟linux没什么区别，第一步，brew install docker nginx， 第二步下载那个shell文件， 第三步运行shell。这个时候本地的27701端口已经跑起来了，电脑已经可以使用，安卓需要https所以麻烦一点，你安装一个mkcert，mac使用固定局域网ip，比如10.10.10.10， 然后用mkcert生成这个ip的证书，下载证书cer后缀的到安卓上，设置 安全里面找 有一个安装证书的装上，nginx的配置文件就用我那个就行了，ssl证书改一改，域名改成10.10.10.10. brew 安装的话一般位置在 /usr/local/etc/nginx/servers目录下的， 配置文件修改好之后brew services restart nginx就好了。此时安卓也能用了。

**Comment by mingwiki** [comment]
电脑单指windows，使用需要安装一个ankisyncd的插件，你网上找一找，mkcert网上也有教程使用很简单，如果还搞不定再截图发邮件问我。

**Comment by mingwiki** [comment]
mac和ios的anki不支持第三方同步，只有安卓和win支持。

**Comment by mingwiki** [comment]
我重写了一遍readme，你再看看，应该很清楚了。

**Comment by pk49800** [comment]
脚本启动报如下错误：
docker: Error response from daemon: Mounts denied:
The path /data/anki is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
已经提前将该文件夹加入文件共享里面了

**Comment by mingwiki** [comment]
用sudo试试

**Comment by mingwiki** [comment]
其实这个地址是存anki数据的，你放任何地方都行，比如你想放在家目录就把那个anki.sh里面的/data/anki替换成/Users/xxx/ankidata

**Comment by pk49800** [comment]
超管权限还是报一样的错，我是在家目录创建的文件夹
➜  anki sudo sh ./anki.sh
74ff5f4d84c423b857bac6a85d4538bcd11b81d8c2c32da67c940608da38cc6d
docker: Error response from daemon: Mounts denied:
The path /data/anki is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.

**Comment by mingwiki** [comment]
这个肯定是路径错了，或者没有添加共享，你cd /data/anki 截图我看看，mac docker的文件共享截图看看

**Comment by mingwiki** [comment]
对不起，我发现是我curl写错了，你应该下错了anki.sh. 
重新下一个，`curl -sOL https://github.com/mingwiki/anki-sync-server/releases/download/v1/anki.sh`

**Comment by pk49800** [comment]
运行起来以后报错无法添加用户
Commands:
  adduser <username> - add a new user
  deluser <username> - delete a user
  lsuser             - list users
  passwd <username>  - change password of a user
# ./ankisyncctl.py lsuser
Traceback (most recent call last):
  File "./ankisyncctl.py", line 82, in <module>
    main()
  File "./ankisyncctl.py", line 76, in main
    cmds[c]()
  File "./ankisyncctl.py", line 37, in lsuser
    users = user_manager.user_list()
  File "/anki/ankisyncd/users.py", line 87, in user_list
    cursor.execute(self.fs("SELECT username FROM auth"))
sqlite3.OperationalError: no such table: auth
# ./ankisysncctl.py adduser pk49800@gmail.com
/bin/sh: 6: ./ankisysncctl.py: not found
# ./ankisyncctl.py adduser pk49800@gmail.com
Enter password for pk49800@gmail.com:
Traceback (most recent call last):
  File "./ankisyncctl.py", line 82, in <module>
    main()
  File "./ankisyncctl.py", line 74, in main
    cmds[c](arg)
  File "./ankisyncctl.py", line 25, in adduser
    user_manager.add_user(username, password)
  File "/anki/ankisyncd/users.py", line 111, in add_user
    self._add_user_to_auth_db(username, password)
  File "/anki/ankisyncd/users.py", line 127, in _add_user_to_auth_db
    cursor.execute(self.fs("INSERT INTO auth VALUES (?, ?)"),
sqlite3.OperationalError: no such table: auth

**Comment by mingwiki** [comment]
加我微信13823330697，我手把手教你，第一个star不能搞丢了。

**Comment by mingwiki** [comment]
你命令都敲错了`./ankisyncctl.py adduser <username>`，用户名没必要是邮箱格式，你就用pk两个字母当用户名就行，`./ankisyncctl.py adduser pk`

**Comment by pk49800** [comment]
不使用邮箱格式的用户名也无法添加呢：
# ./ankisyncctl.py adduser pk49800
Enter password for pk49800:
Traceback (most recent call last):
  File "./ankisyncctl.py", line 82, in <module>
    main()
  File "./ankisyncctl.py", line 74, in main
    cmds[c](arg)
  File "./ankisyncctl.py", line 25, in adduser
    user_manager.add_user(username, password)
  File "/anki/ankisyncd/users.py", line 111, in add_user
    self._add_user_to_auth_db(username, password)
  File "/anki/ankisyncd/users.py", line 127, in _add_user_to_auth_db
    cursor.execute(self.fs("INSERT INTO auth VALUES (?, ?)"),
sqlite3.OperationalError: no such table: auth
# ./ankisyncctl.py adduser pk
Enter password for pk:
Traceback (most recent call last):
  File "./ankisyncctl.py", line 82, in <module>
    main()
  File "./ankisyncctl.py", line 74, in main
    cmds[c](arg)
  File "./ankisyncctl.py", line 25, in adduser
    user_manager.add_user(username, password)
  File "/anki/ankisyncd/users.py", line 111, in add_user
    self._add_user_to_auth_db(username, password)
  File "/anki/ankisyncd/users.py", line 127, in _add_user_to_auth_db
    cursor.execute(self.fs("INSERT INTO auth VALUES (?, ?)"),
sqlite3.OperationalError: no such table: auth
#
