### ISSUE TITLE
发生网络错误：⁨error sending request for url (): error trying to connect: record overflow⁩

### ISSUE THREAD

**Issue by yifan0414** [mingwiki/anki-sync-server#2]
使用的腾讯云的服务器，服务器端配置一切顺利，使用站长端口工具显示端口也打开了，但在mac上用anki同步时就显示上面的错误，请问为什么呢？

**Comment by mingwiki** [comment]
安卓使用有问题吗，mac上点网络，然后强制同步试试。

**Comment by Love4yzp** [comment]
Still not working on my windows 11, Anki version is 2.1.49.
But using Anki for Android is ok!
