### ISSUE TITLE
更新后无法同步数据

### ISSUE THREAD

**Issue by pk49800** [mingwiki/anki-sync-server#4]
更新后无法同步数据，尝试修改用户信息失败
root@44fe9b7f5896:/app# ./ankisyncctl.py lsuser
pk49800@gmail.com
root@44fe9b7f5896:/app#
Display all 486 possibilities? (y or n)
root@44fe9b7f5896:/app# ./ankisyncctl.py passwd pk49800@gmail.com
Enter password for pk49800@gmail.com:
Traceback (most recent call last):
  File "/app/./ankisyncctl.py", line 82, in <module>
    main()
  File "/app/./ankisyncctl.py", line 74, in main
    cmds[c](arg)
  File "/app/./ankisyncctl.py", line 52, in passwd
    user_manager.set_password_for_user(username, password)
  File "/app/ankisyncd/users.py", line 142, in set_password_for_user
    cursor.execute(self.fs("UPDATE auth SET hash=? WHERE username=?"), (hash, username))
sqlite3.OperationalError: attempt to write a readonly database

**Comment by mingwiki** [comment]
你怎么更新的？重新建个账号试试 账户名没必要是邮件

**Comment by pk49800** [comment]
添加新账户也不行，好像是目录权限问题无法写入，以前用着没问题的，今天看到更新就git pull了一下
root@44fe9b7f5896:/app# ./ankisyncctl.py adduser pk49800
Enter password for pk49800:
Traceback (most recent call last):
  File "/app/./ankisyncctl.py", line 82, in <module>
    main()
  File "/app/./ankisyncctl.py", line 74, in main
    cmds[c](arg)
  File "/app/./ankisyncctl.py", line 25, in adduser
    user_manager.add_user(username, password)
  File "/app/ankisyncd/users.py", line 111, in add_user
    self._add_user_to_auth_db(username, password)
  File "/app/ankisyncd/users.py", line 127, in _add_user_to_auth_db
    cursor.execute(self.fs("INSERT INTO auth VALUES (?, ?)"),
sqlite3.OperationalError: attempt to write a readonly database

**Comment by mingwiki** [comment]
如果是目录权限问题就用chmod chown 修改一下再用

**Comment by pk49800** [comment]
修改了目录所有者和权限都不行，已经把目录改成容器里的目录权限了（nobody）
![截屏2022-07-26 20 29 34](https://user-images.githubusercontent.com/36910388/181006003-26246e89-b93d-4610-8570-80829014736a.png)
依然是报无法写入数据库的错
root@5ba5119ecdac:/app# ./ankisyncctl.py lsuser
pk49800@gmail.com
root@5ba5119ecdac:/app# ./ankisyncctl.py passwd pk49800@gmail.com
Enter password for pk49800@gmail.com:
Traceback (most recent call last):
  File "/app/./ankisyncctl.py", line 82, in <module>
    main()
  File "/app/./ankisyncctl.py", line 74, in main
    cmds[c](arg)
  File "/app/./ankisyncctl.py", line 52, in passwd
    user_manager.set_password_for_user(username, password)
  File "/app/ankisyncd/users.py", line 142, in set_password_for_user
    cursor.execute(self.fs("UPDATE auth SET hash=? WHERE username=?"), (hash, username))
sqlite3.OperationalError: attempt to write a readonly database

**Comment by pk49800** [comment]
我发容器内的data文件夹所有者是root，而且无法更改所有权
![截屏2022-07-26 21 23 05](https://user-images.githubusercontent.com/36910388/181016410-1143285a-2e2d-44ac-978f-748b5ec9f91b.png)

**Comment by mingwiki** [comment]
chmod -r 777 /data/anki 你这只有读取权限没有写入的

**Comment by mingwiki** [comment]
把db文件给777 权限

**Comment by mingwiki** [comment]
改外面挂载的那个anki 文件夹 chmod 777 anki

**Comment by pk49800** [comment]
改完权限仍然不可写
![截屏2022-07-27 09 14 14](https://user-images.githubusercontent.com/36910388/181139134-84d48072-dcf8-40f8-9769-36c3fff90b22.png)
![截屏2022-07-27 09 14 48](https://user-images.githubusercontent.com/36910388/181139188-90b4710c-1c9b-4ba9-8151-9af56151b52b.png)

**Comment by pk49800** [comment]
还有请教一下，为什么启动后生成两个不同的image
![截屏2022-07-27 09 18 20](https://user-images.githubusercontent.com/36910388/181139531-ecf65798-c539-449a-869f-f46cf3deaafe.png)

**Comment by mingwiki** [comment]
image 只是镜像  用docker image prune去掉多余的image

**Comment by mingwiki** [comment]
把collections 备份一下 然后把两个db文件删了 建立一个新账户

**Comment by pk49800** [comment]
我试过下载其他人做的anki-server也是这样，无法写入数据，发现所有目录都是不可写的，根本无法创建新账户

**Comment by mingwiki** [comment]
你用sudo docker-compose up -d 起一下 用root权限

**Comment by pk49800** [comment]
绝了，不给用root权限运行
![截屏2022-07-27 10 01 39](https://user-images.githubusercontent.com/36910388/181144327-f61ea113-7de4-45ec-b4f3-492b170eddc6.png)

**Comment by mingwiki** [comment]
这我就无法理解了 db文件可以删的吧 记得备份就行了 建立新账户会重新生成db文件

**Comment by pk49800** [comment]
只能在宿主机上删，在容器里不能对任何文件进行修改删除的操作，也就是，无法修改和创建任何内容

**Comment by mingwiki** [comment]
你改过compose文件吗，用户是什么权限

**Comment by pk49800** [comment]
改了映射目录，不改会报错，改成本地环境的,用户权限没改啊，以前用得好好的
```yml
version: "3.5"
services:
  app:
    restart: unless-stopped
    build: .
    container_name: anki
    image: mingwiki/anki-sync-server:v1.2
    ports:
      - "27701:27701"
    volumes:
      - /Users/pk49800/data/anki:/data
```

**Comment by pk49800** [comment]
我感觉要重装docker环境了，如果你的没问题的话

**Comment by mingwiki** [comment]
把所有容器停掉 
docker container prune
docker image prune 
docker network prune
这几个执行一遍，然后再docker-compose up -d
docker默认就是root权限 不应该出现这种情况

**Comment by mingwiki** [comment]
另外我建议你把data目录改为root
chown -R root:root data
![image](https://user-images.githubusercontent.com/7548568/181149046-d6fe6ffb-cb49-4ac1-9134-2e7661649562.png)

**Comment by pk49800** [comment]
只要是对容器内的文件或者目录进行修改的操作都失败
![截屏2022-07-27 10 44 46](https://user-images.githubusercontent.com/36910388/181149511-13301c23-cdcf-4df2-a4e8-c920defcab84.png)

**Comment by pk49800** [comment]
看来得重装了，惨，你进入容器可以修改权限？

**Comment by mingwiki** [comment]
在外面改 不是在里面

**Comment by mingwiki** [comment]
跟docker没有关系 就是单纯的权限给错了

**Comment by pk49800** [comment]
MAC没有root组，我试试改成admin组

**Comment by mingwiki** [comment]
反正保证运行docker的账户和data账户一致 无特殊需求不要用nobody nogroup这种分类

**Comment by pk49800** [comment]
神奇的是，我外面改了权限以后，里面文件夹所有者变成nobody了，还是无法写入数据
![截屏2022-07-27 10 55 03](https://user-images.githubusercontent.com/36910388/181150791-88aaa25c-2e90-457e-8dc6-b188f559c728.png)
![截屏2022-07-27 10 55 54](https://user-images.githubusercontent.com/36910388/181150889-33bef1c2-2af3-4a4a-9597-32d14e7f2c30.png)
![截屏2022-07-27 10 56 17](https://user-images.githubusercontent.com/36910388/181150923-f16f6092-eea7-4e56-9630-aea582d1e3f5.png)

**Comment by mingwiki** [comment]
内外权限不一致吧，你用这个 后面加个rw
```
version: "3.5"
services:
  anki:
    restart: unless-stopped
    container_name: anki
    image: mingwiki/anki-sync-server:v1.2
    ports:
      - "27701:27701"
    volumes:
      - /mnt/omv/anki:/data:rw
```

**Comment by pk49800** [comment]
还是不行，无解了

**Comment by mingwiki** [comment]
没道理不行啊 你有先down 后up吗 ，data权限给700试试

**Comment by pk49800** [comment]
有啊，一样不行

**Comment by pk49800** [comment]
我这docker环境有没有问题？
```bash
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:46 2022
 OS/Arch:           linux/amd64
 Context:           rootless
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:00:51 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by mingwiki** [comment]
感觉没关系 
chown -R pk49800:staff /data/anki
chmod 700 /data/anki
docker-compose down && docker-compose up -d
试试 不行的话 可以试试虚拟机装linux  我这没mac 测不了

**Comment by pk49800** [comment]
用docker不行，我用lima可以，用的Ubuntu容器运行
![截屏2022-07-27 19 46 14](https://user-images.githubusercontent.com/36910388/181239125-bb112796-e340-4641-b2de-208eea26887e.png)

![截屏2022-07-27 19 44 53](https://user-images.githubusercontent.com/36910388/181238891-11f50f0e-761b-40b2-90b7-5c2b0727d77b.png)

**Comment by mingwiki** [comment]
哦好的 问题解决就好
